name: censimento_idranti_aib
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_map: ^7.0.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png